# Generated by Django 2.2.1 on 2019-05-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='movie',
        ),
        migrations.AddField(
            model_name='news',
            name='movies',
            field=models.ManyToManyField(to='main.Movies'),
        ),
    ]
