# Generated by Django 2.2.1 on 2019-06-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190514_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='url',
            field=models.URLField(default='https://www.archipelagoliving.net/Archipelago/media/Hero-images/Default-coming-soon-(1).jpg'),
            preserve_default=False,
        ),
    ]
