# Generated by Django 2.2.1 on 2019-06-04 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_movies_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='amount',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
            preserve_default=False,
        ),
    ]
