"""
Django settings for movieJazz project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!vny0r!5erx+wlee%kw7z59s^y22sb+6fqpl===l7!d))0@o2+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'movieJazz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'movieJazz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# CSRF_COOKIE_SECURE determines whether to use a secure cookie for the CSRF cookie. 
# If this is set to True, the cookie will be marked as “secure”, 
# which means browsers may ensure that the cookie is only sent with 
# an HTTPS connection.
CSRF_COOKIE_SECURE = True

# SESSION_COOKIE_SECURE determines whether to use a secure cookie for the session 
# cookie. If this is set to True, the cookie will be marked as “secure”, 
# which means browsers may ensure that the cookie is only sent under 
# an HTTPS connection.
SESSION_COOKIE_SECURE = True

# CSRF_COOKIE_HTTPONLY determines whether to use HttpOnly flag on the CSRF cookie.
# If this is set to True, client-side JavaScript will not to be able to access 
# the CSRF cookie
CSRF_COOKIE_HTTPONLY = True

# SESSION_COOKIE_HTTPONLY determines whether to use HttpOnly flag on the session cookie.
# If this is set to True, client-side JavaScript will not to be able to access the session
# cookie.
SESSION_COOKIE_HTTPONLY = True

# If SECURE_SSL_REDIRECT is True, the SecurityMiddleware redirects all non-HTTPS requests 
# to HTTPS (except for those URLs matching a regular expression listed in SECURE_REDIRECT_EXEMPT).
SECURE_SSL_REDIRECT = True

# SESSION_COOKIE_AGE is a integer value which determines the amount of seconds
# a cookie is in session. Currently the cookie age is set to 3600 seconds, or 1 hour
# so the cookie expires in 1 hour and users are logged out. 
SESSION_COOKIE_AGE = 3600

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

AUTH_USER_MODEL = 'main.Users'