# Generated by Django 2.2.1 on 2019-05-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Movie', 'Movie'), ('Theater', 'Theater'), ('Offer', 'Offer'), ('Authentification', 'Authentification'), ('Transaction', 'Transaction'), ('Others', 'Others')], max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('answer', models.CharField(default=None, max_length=5000)),
            ],
        ),
    ]
