# Generated by Django 2.2.1 on 2019-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
